### PR TITLE
Added docker badges

### PR DESCRIPTION
**Pull request by sumitkharche**
## Description
Added docker version and download badges

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sumitkharche** [comment]
@amuraru Thanks for the review.

**Comment by amuraru** [comment]
thanks for your contribution @sumitkharche !

**Comment by sumitkharche** [comment]
> thanks for your contribution @sumitkharche !

Is this PR consider for adobe Squashtoberfest

**Comment by sumitkharche** [comment]
Is this PR consider for adobe Squashtoberfest?

    On Monday, 21 October, 2019, 04:19:10 pm IST, Adrian Muraru <notifications@github.com> wrote:  
 
 
Merged #88 into master.

**Comment by amuraru** [comment]
> Is this PR consider for adobe Squashtoberfest?

It should, yes.

**Pull request merged**
